In [336]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA
from sklearn.preprocessing import OrdinalEncoder, StandardScaler
from sklearn.pipeline import make_pipeline
from sklearn.model_selection import train_test_split
from sklearn.linear_model import SGDRegressor
import numpy as np

In [337]:
df = pd.read_csv("Data/PopulationByAgeSex.csv", index_col="Time", parse_dates=True)
print(df.shape)
df.head()

(66893, 70)


Id  LocID     Location  PopMale_0_4  PopFemale_0_4  PopTotal_0_4  \
Time                                                                           
1950-01-01   1      4  Afghanistan      630.044        661.578      1291.622   
1951-01-01   2      4  Afghanistan      641.199        673.293      1314.492   
1952-01-01   3      4  Afghanistan      650.825        669.274      1320.099   
1953-01-01   4      4  Afghanistan      659.896        663.606      1323.502   
1954-01-01   5      4  Afghanistan      670.694        663.295      1333.989   

            PopMale_5_9  PopFemale_5_9  PopTotal_5_9  PopMale_10_14  ...  \
Time                                                                 ...   
1950-01-01      516.206        487.335      1003.541        461.378  ...   
1951-01-01      525.302        502.402      1027.704        465.611  ...   
1952-01-01      533.097        521.672      1054.769        471.928  ...   
1953-01-01      538.351        541.216      1079.567        480.448  ...   
1954-01-01      540.820        557.196      1098.016        489.780  ...   

            PopMale_95_99  PopFemale_95_99  PopTotal_95_99  PopMale_100Plus  \
Time                                                                          
1950-01-01          0.004            0.003           0.007              0.0   
1951-01-01          0.007            0.005           0.012              0.0   
1952-01-01          0.012            0.009           0.021              0.0   
1953-01-01          0.015            0.013           0.028              0.0   
1954-01-01          0.014            0.011           0.025              0.0   

            PopFemale_100Plus  PopTotal_100Plus   PopMale  PopFemale  \
Time                                                                   
1950-01-01                0.0               0.0  4099.243   3652.874   
1951-01-01                0.0               0.0  4134.756   3705.395   
1952-01-01                0.0               0.0  4174.450   3761.546   
1953-01-01                0.0               0.0  4218.336   3821.348   
1954-01-01                0.0               0.0  4266.484   3884.832   

            PopTotal  YearDataCompleted  
Time                                     
1950-01-01  7752.117                  1  
1951-01-01  7840.151                  1  
1952-01-01  7935.996                  1  
1953-01-01  8039.684                  1  
1954-01-01  8151.316                  1  

[5 rows x 70 columns]

In [338]:
# select Target and Features
#Targets
y = df['PopTotal']
y= y.values.reshape(-1,1)
print(f"{y} \n {y.shape}")

#Features
x = df.drop(['PopTotal', 'Location'], axis =1)
print(f"{x.head()} \n {x.shape}")

[[ 7752.117]
 [ 7840.151]
 [ 7935.996]
 ...
 [30959.811]
 [30964.052]
 [30965.421]] 
 (66893, 1)
            Id  LocID  PopMale_0_4  PopFemale_0_4  PopTotal_0_4  PopMale_5_9  \
Time                                                                           
1950-01-01   1      4      630.044        661.578      1291.622      516.206   
1951-01-01   2      4      641.199        673.293      1314.492      525.302   
1952-01-01   3      4      650.825        669.274      1320.099      533.097   
1953-01-01   4      4      659.896        663.606      1323.502      538.351   
1954-01-01   5      4      670.694        663.295      1333.989      540.820   

            PopFemale_5_9  PopTotal_5_9  PopMale_10_14  PopFemale_10_14  ...  \
Time                                                                     ...   
1950-01-01        487.335      1003.541        461.378          423.326  ...   
1951-01-01        502.402      1027.704        465.611          427.618  ...   
1952-01-01        521.

In [339]:
reduct = PCA(n_components=36)
x = reduct.fit_transform(x)
x.shape

(66893, 36)

In [340]:
#preprocessing:
#encoder features
encoder_x = OrdinalEncoder()
encoder_x = encoder_x.fit_transform(x)
print(encoder_x)

[[17902. 40118. 16641. ... 19798. 14351. 49637.]
 [17982. 40221. 16803. ... 21333. 14365. 48762.]
 [18070. 40317. 16886. ... 26168. 15679. 43019.]
 ...
 [27620. 18007. 43655. ... 20687. 21133. 22175.]
 [27618. 17836. 43782. ... 22263. 21361. 22927.]
 [27617. 17676. 43930. ... 23641. 21200. 23287.]]


In [341]:
#encoder targets
encoder_y = OrdinalEncoder()
encoder_y= encoder_y.fit_transform(y)
print(encoder_y)

[[17634.]
 [17705.]
 [17788.]
 ...
 [26980.]
 [26981.]
 [26982.]]


In [342]:
#create a train set and test set
x_train, x_test, y_train, y_test = train_test_split(encoder_x, encoder_y, test_size=.2)
print(f'pour le train: {x_train.shape}, {y_train.shape}')
print(f'pour le test: {x_test.shape}, {y_test.shape}')

pour le train: (53514, 36), (53514, 1)
pour le test: (13379, 36), (13379, 1)


In [343]:
#modeling and normalisation
model = make_pipeline(StandardScaler(), SGDRegressor())
model.fit(x_train, y_train)

C:\Users\MOHAM\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\utils\validation.py:985: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Pipeline(steps=[('standardscaler', StandardScaler()),
                ('sgdregressor', SGDRegressor())])

In [344]:
#Evaluate models
model.score(x_test, y_test)

0.9990733855186597

In [345]:
# voir la prediction du model
predict = model.predict(encoder_x[0:2])
print(f"prediction: {predict}, targets: {encoder_y[0:2]}")

prediction: [17653.66867824 17727.99448549], targets: [[17634.]
 [17705.]]
